# Generated by Django 5.0.1 on 2024-01-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('id_seller', models.CharField(max_length=200)),
                ('discounted_price', models.CharField(max_length=200)),
                ('original_price', models.CharField(max_length=200)),
                ('discount_percentage', models.CharField(max_length=200)),
                ('product_rating', models.CharField(max_length=200)),
                ('number_of_reviews', models.CharField(max_length=200)),
                ('supplier', models.CharField(max_length=200)),
                ('supplier_rating', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
